export const GITHUB_USER_REQUEST = 'githubUser/GITHUB_USER_REQUEST'
export const GITHUB_USER_FAILURE = 'githubUser/GITHUB_USER_FAILURE'
export const GITHUB_USER_SUCCESS = 'githubUser/GITHUB_USER_SUCCESS'
